include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "bin/cache/**"
    - "**/*.config.dart"
    - "*.config.dart"
    - "**.gr.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - modules/**
    - "**/*.mocks.dart"    
    - flutter/**
    - sprout/**
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    import_of_legacy_library_into_null_safe: ignore

linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
    prefer_mixin: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    prefer_relative_imports: false
    unnecessary_getters_setters: false
    avoid_function_literals_in_foreach_calls: false
    invalid_annotation_target: false
    prefer_const_constructors: false
    prefer_final_fields: false