name: ui_collection
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  shared_preferences: 2.0.13
  ntp: 2.0.0
  injectable: 1.5.3
  get_it: 7.2.0
  dartz: 0.10.1
  package_info: 2.0.2
  google_fonts: 3.0.1
  font_awesome_flutter: 10.1.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  dio: ^4.0.6
  route_observer_mixin: ^1.7.0
  shimmer: 2.0.0
  provider: 6.0.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.8
  # bloc_test: 9.0.2
  flutter_lints: ^1.0.4
  freezed: 2.0.3+1
  json_serializable: ^6.3.1

  injectable_generator: 1.5.3

flutter:

  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
